service: techcost-scraper

provider:
  name: aws
  runtime: nodejs10.x

functions:
  scrapeAndSave:
    handler: handler.scrapeAndSave
    events:
      - http:
          path: scrape-result/
          method: POST
          cors: true

  oneTimeScrape:
    handler: handler.oneTimeScrape
    events:
      - http:
          path: scrape-result/
          method: GET
          cors: true
  updateCronRequest:
    handler: handler.updateCronRequest
    events:
      - http:
          path: cron-request/{cron_request_id}
          method: PATCH
          request:
            parameters:
              paths:
                cron_request_id: true
          cors: true
  createCronRequest: 
    handler: handler.updateCronRequest
    events:
      - http:
          path: cron-request
          method: POST
          cors: true
  createUser: 
    handler: handler.createUser
    events:
      - http:
          path: user
          method: POST
          cors: true


